@php($editing = isset($user))
<div class="grid gap-5 sm:grid-cols-2">
    <div class="sm:col-span-2"><label for="name" class="mb-2 block text-sm font-medium text-slate-200">Imię i nazwisko</label><input id="name" name="name" value="{{ old('name', $user->name ?? '') }}" required class="w-full rounded-xl border border-white/[0.08] bg-[#080b1b] px-4 py-3 text-white outline-none focus:border-indigo-500">@error('name')<p class="mt-2 text-sm text-rose-400">{{ $message }}</p>@enderror</div>
    <div class="sm:col-span-2"><label for="email" class="mb-2 block text-sm font-medium text-slate-200">Adres e-mail</label><input id="email" name="email" type="email" value="{{ old('email', $user->email ?? '') }}" required class="w-full rounded-xl border border-white/[0.08] bg-[#080b1b] px-4 py-3 text-white outline-none focus:border-indigo-500">@error('email')<p class="mt-2 text-sm text-rose-400">{{ $message }}</p>@enderror</div>
    <div class="sm:col-span-2"><label for="role" class="mb-2 block text-sm font-medium text-slate-200">Poziom uprawnień</label><select id="role" name="role" required @disabled($editing && auth()->id() === $user->id) class="w-full rounded-xl border border-white/[0.08] bg-[#080b1b] px-4 py-3 text-white outline-none focus:border-indigo-500">@foreach($roles as $role)<option value="{{ $role->value }}" @selected(old('role', $user->role->value ?? 'user') === $role->value)>{{ $role->label() }}</option>@endforeach</select>@if($editing && auth()->id() === $user->id)<input type="hidden" name="role" value="admin"><p class="mt-2 text-xs text-slate-500">Nie możesz odebrać roli administratora własnemu kontu.</p>@endif @error('role')<p class="mt-2 text-sm text-rose-400">{{ $message }}</p>@enderror</div>
    <div><label for="password" class="mb-2 block text-sm font-medium text-slate-200">Hasło {{ $editing ? '(opcjonalnie)' : '' }}</label><input id="password" name="password" type="password" @required(!$editing) autocomplete="new-password" class="w-full rounded-xl border border-white/[0.08] bg-[#080b1b] px-4 py-3 text-white outline-none focus:border-indigo-500">@error('password')<p class="mt-2 text-sm text-rose-400">{{ $message }}</p>@enderror</div>
    <div><label for="password_confirmation" class="mb-2 block text-sm font-medium text-slate-200">Powtórz hasło</label><input id="password_confirmation" name="password_confirmation" type="password" @required(!$editing) autocomplete="new-password" class="w-full rounded-xl border border-white/[0.08] bg-[#080b1b] px-4 py-3 text-white outline-none focus:border-indigo-500"></div>
</div>
<div class="mt-7 flex justify-end gap-3"><a href="{{ route('admin.users.index') }}" class="rounded-xl border border-white/10 px-5 py-3 text-sm font-medium text-slate-300 hover:bg-white/5">Anuluj</a><button class="rounded-xl bg-indigo-500 px-5 py-3 text-sm font-semibold text-white shadow-lg shadow-indigo-500/20 hover:bg-indigo-400">{{ $editing ? 'Zapisz zmiany' : 'Dodaj użytkownika' }}</button></div>
