<x-warehouse-shell title="Zamrażarki" description="Codzienna kontrola temperatury i 30-dniowy rejestr mycia." root-label="Zamrażarki" root-route="freezers.index">
<x-slot:actions><button type="button" onclick="document.querySelector('#new-freezer').classList.toggle('hidden')" class="rounded-xl bg-indigo-500 px-4 py-2.5 text-sm font-semibold text-white">+ Dodaj zamrażarkę</button></x-slot:actions>
<div class="mb-6 grid gap-4 sm:grid-cols-3">
    <div class="rounded-2xl border border-indigo-500/20 bg-indigo-500/10 p-5"><p class="text-xs font-medium uppercase tracking-wider text-indigo-300">Liczba zamrażarek</p><p class="mt-2 text-2xl font-bold text-white">{{ $freezers->count() }}</p></div>
    <div class="rounded-2xl border {{ $temperatureDue ? 'border-rose-500/20 bg-rose-500/10' : 'border-emerald-500/20 bg-emerald-500/10' }} p-5"><p class="text-xs font-medium uppercase tracking-wider text-slate-400">Kontrola temperatury wymagana</p><p class="mt-2 text-2xl font-bold {{ $temperatureDue ? 'text-rose-300' : 'text-emerald-300' }}">{{ $temperatureDue }}</p></div>
    <div class="rounded-2xl border {{ $cleaningDue ? 'border-amber-500/20 bg-amber-500/10' : 'border-emerald-500/20 bg-emerald-500/10' }} p-5"><p class="text-xs font-medium uppercase tracking-wider text-slate-400">Mycie wymagane</p><p class="mt-2 text-2xl font-bold {{ $cleaningDue ? 'text-amber-300' : 'text-emerald-300' }}">{{ $cleaningDue }}</p></div>
</div>
<form id="new-freezer" method="POST" action="{{ route('freezers.store') }}" class="mb-6 {{ $errors->any()?'':'hidden' }} rounded-2xl border border-white/[0.06] bg-[#0d1024] p-5">@csrf
    <h2 class="font-semibold text-white">Nowa zamrażarka</h2><p class="mt-1 text-xs text-slate-500">Typ szczepionki przypiszesz później w szczegółach zamrażarki.</p>
    <div class="mt-4"><label class="mb-2 block text-xs text-slate-400">Numer zamrażarki</label><input name="number" value="{{ old('number') }}" required class="w-full rounded-xl bg-[#080b1b] px-4 py-3"></div>
    @if($errors->any())<p class="mt-3 text-sm text-rose-400">{{ $errors->first() }}</p>@endif
    <div class="mt-5 flex justify-end"><button class="rounded-xl bg-emerald-500 px-6 py-3 font-semibold text-slate-950">Zapisz zamrażarkę</button></div>
</form>
<section class="grid gap-4 xl:grid-cols-2">@forelse($freezers as $freezer)
<a href="{{ route('freezers.show',$freezer) }}" class="rounded-2xl border border-white/[0.06] bg-[#0d1024] p-5 transition hover:border-indigo-500/30 hover:bg-white/[0.03]">
    <div class="flex items-start justify-between gap-4"><div><p class="text-xs text-slate-500">Zamrażarka</p><h2 class="mt-1 text-xl font-bold text-white">{{ $freezer->number }}</h2><p class="mt-2 text-sm {{ $freezer->currentAssignment?'text-indigo-300':'text-slate-500' }}">{{ $freezer->currentAssignment?->vaccineType?->name ?? 'Obecnie pusta' }}</p></div><span class="rounded-full px-2.5 py-1 text-xs {{ $freezer->temperature_checked_today?'bg-emerald-500/10 text-emerald-300':'bg-rose-500/10 text-rose-300' }}">{{ $freezer->temperature_checked_today?'Temperatura OK':'Sprawdź temperaturę' }}</span></div>
    <div class="mt-5 grid grid-cols-2 gap-3"><div class="rounded-xl bg-white/[0.03] p-3"><p class="text-xs text-slate-500">Ostatnia temperatura</p><b class="mt-1 block text-white">{{ $freezer->latestTemperatureCheck ? number_format((float)$freezer->latestTemperatureCheck->temperature_c,1,',',' ').' °C' : 'Brak pomiaru' }}</b><p class="mt-1 text-[10px] text-slate-600">{{ $freezer->latestTemperatureCheck?->checked_at?->format('d.m.Y H:i') }}</p></div><div class="rounded-xl bg-white/[0.03] p-3"><p class="text-xs text-slate-500">Ważność mycia</p><b class="mt-1 block {{ $freezer->cleaning_is_valid?'text-emerald-300':'text-amber-300' }}">{{ $freezer->latestCleaning?->valid_until?->format('d.m.Y') ?? 'Brak mycia' }}</b><p class="mt-1 text-[10px] text-slate-600">{{ $freezer->cleaning_is_valid?'Aktualne':'Wymaga mycia' }}</p></div></div>
</a>@empty<div class="col-span-full rounded-2xl border border-dashed border-white/10 py-20 text-center text-slate-500">Brak zamrażarek. Dodaj pierwszą zamrażarkę.</div>@endforelse</section>
</x-warehouse-shell>
