<x-warehouse-shell :title="'Zamrażarka '.$freezer->number" :description="$freezer->currentAssignment ? 'Aktualnie: '.$freezer->currentAssignment->vaccineType->name : 'Zamrażarka jest obecnie pusta'" root-label="Zamrażarki" root-route="freezers.index">
<x-slot:breadcrumbs><span>/ {{ $freezer->number }}</span></x-slot:breadcrumbs>
<div class="mb-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">
    <div class="rounded-2xl border border-indigo-500/20 bg-indigo-500/10 p-5"><p class="text-xs uppercase tracking-wider text-slate-400">Aktualna zawartość</p><p class="mt-2 text-xl font-bold {{ $freezer->currentAssignment?'text-indigo-200':'text-slate-400' }}">{{ $freezer->currentAssignment?->vaccineType?->name ?? 'Pusta' }}</p>@if($freezer->currentAssignment)<p class="mt-2 text-xs text-slate-500">Od {{ $freezer->currentAssignment->started_at->format('d.m.Y') }}</p>@endif</div>
    <div class="rounded-2xl border {{ $freezer->temperature_checked_today?'border-emerald-500/20 bg-emerald-500/10':'border-rose-500/20 bg-rose-500/10' }} p-5"><p class="text-xs uppercase tracking-wider text-slate-400">Dzisiejsza kontrola temperatury</p><p class="mt-2 text-xl font-bold {{ $freezer->temperature_checked_today?'text-emerald-300':'text-rose-300' }}">{{ $freezer->temperature_checked_today?'Wykonana':'Wymagana' }}</p>@if($freezer->latestTemperatureCheck)<p class="mt-2 text-xs text-slate-500">{{ $freezer->latestTemperatureCheck->checked_at->format('d.m.Y H:i') }} · {{ $freezer->latestTemperatureCheck->recorder?->name ?? 'usunięty użytkownik' }}</p>@endif</div>
    <div class="rounded-2xl border {{ $freezer->cleaning_is_valid?'border-emerald-500/20 bg-emerald-500/10':'border-amber-500/20 bg-amber-500/10' }} p-5"><p class="text-xs uppercase tracking-wider text-slate-400">Ważność mycia</p><p class="mt-2 text-xl font-bold {{ $freezer->cleaning_is_valid?'text-emerald-300':'text-amber-300' }}">{{ $freezer->latestCleaning?->valid_until?->format('d.m.Y') ?? 'Mycie wymagane' }}</p>@if($freezer->latestCleaning)<p class="mt-2 text-xs text-slate-500">{{ $freezer->latestCleaning->cleaned_at->format('d.m.Y H:i') }} · {{ $freezer->latestCleaning->recorder?->name ?? 'usunięty użytkownik' }}</p>@endif</div>
</div>
<section class="mb-6 rounded-2xl border border-white/[0.06] bg-[#0d1024] p-6"><div class="flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div><h2 class="font-bold text-white">Przypisanie typu szczepionki</h2><p class="mt-1 text-xs text-slate-500">Nowe przypisanie automatycznie zamknie poprzedni okres.</p></div>@if($freezer->currentAssignment)<form method="POST" action="{{ route('freezers.assignments.end',$freezer) }}" class="flex gap-2">@csrf<input name="ended_at" type="date" value="{{ now()->format('Y-m-d') }}" required class="rounded-lg bg-[#080b1b] px-3 py-2 text-sm"><button class="rounded-lg border border-amber-500/30 px-3 py-2 text-sm font-semibold text-amber-300">Oznacz jako pustą</button></form>@endif</div>
<form method="POST" action="{{ route('freezers.assignments.store',$freezer) }}" class="mt-5 grid gap-3 sm:grid-cols-[1fr_220px_auto]">@csrf<select name="vaccine_type_id" required class="rounded-xl bg-[#080b1b] px-4 py-3"><option value="">Wybierz typ szczepionki</option>@foreach($types as $type)<option value="{{ $type->id }}">{{ $type->name }}</option>@endforeach</select><input name="started_at" type="date" value="{{ now()->format('Y-m-d') }}" required class="rounded-xl bg-[#080b1b] px-4 py-3"><button class="rounded-xl bg-indigo-500 px-5 py-3 font-semibold text-white">Przypisz typ</button></form>@if($errors->has('vaccine_type_id')||$errors->has('started_at')||$errors->has('ended_at'))<p class="mt-3 text-sm text-rose-400">{{ $errors->first() }}</p>@endif
<div class="mt-6 overflow-x-auto"><table class="w-full min-w-[650px] text-left text-sm"><thead class="border-b border-white/[0.06] text-xs text-slate-500"><tr><th class="py-3">Typ szczepionki</th><th class="py-3">Od</th><th class="py-3">Do</th><th class="py-3">Wprowadził</th></tr></thead><tbody>@forelse($freezer->vaccineAssignments as $assignment)<tr class="border-b border-white/[0.04]"><td class="py-3 font-medium text-white">{{ $assignment->vaccineType->name }}</td><td class="py-3 text-slate-400">{{ $assignment->started_at->format('d.m.Y') }}</td><td class="py-3 text-slate-400">{{ $assignment->ended_at?->format('d.m.Y') ?? 'obecnie' }}</td><td class="py-3 text-slate-500">{{ $assignment->recorder?->name ?? 'migracja danych' }}</td></tr>@empty<tr><td colspan="4" class="py-8 text-center text-slate-500">Brak historii przypisań.</td></tr>@endforelse</tbody></table></div>
</section>
<div class="grid gap-6 xl:grid-cols-2">
<section class="rounded-2xl border border-white/[0.06] bg-[#0d1024] p-6"><h2 class="font-bold text-white">Kontrola temperatury</h2><form method="POST" action="{{ route('freezers.temperature.store',$freezer) }}" class="mt-5 grid gap-3 sm:grid-cols-2">@csrf<div><label class="mb-2 block text-xs text-slate-400">Temperatura (°C)</label><input name="temperature_c" value="{{ old('temperature_c') }}" type="number" step="0.01" required class="w-full rounded-xl bg-[#080b1b] px-4 py-3"></div><div><label class="mb-2 block text-xs text-slate-400">Data i godzina kontroli</label><input name="checked_at" value="{{ old('checked_at',now()->format('Y-m-d\TH:i')) }}" type="datetime-local" required class="w-full rounded-xl bg-[#080b1b] px-4 py-3"></div>@if($errors->has('temperature_c')||$errors->has('checked_at'))<p class="sm:col-span-2 text-sm text-rose-400">{{ $errors->first() }}</p>@endif<button class="sm:col-span-2 rounded-xl bg-indigo-500 px-4 py-3 font-semibold text-white">Zapisz kontrolę temperatury</button></form><div class="mt-6 space-y-3"><h3 class="text-sm font-semibold text-slate-300">Historia temperatur</h3>@forelse($freezer->temperatureChecks as $check)<article class="rounded-xl bg-white/[0.03] p-4"><div class="flex justify-between gap-3"><div><p class="text-sm text-slate-300">{{ $check->checked_at->format('d.m.Y H:i') }}</p><p class="mt-1 text-xs text-slate-600">{{ $check->recorder?->name ?? 'usunięty użytkownik' }}</p></div><b class="text-lg text-cyan-300">{{ number_format((float)$check->temperature_c,1,',',' ') }} °C</b></div></article>@empty<p class="py-8 text-center text-sm text-slate-500">Brak kontroli temperatury.</p>@endforelse</div></section>
<section class="rounded-2xl border border-white/[0.06] bg-[#0d1024] p-6"><h2 class="font-bold text-white">Mycie zamrażarki</h2><p class="mt-1 text-xs text-slate-500">Każdy wpis jest ważny przez 30 dni.</p><form method="POST" action="{{ route('freezers.cleaning.store',$freezer) }}" class="mt-5">@csrf<label class="mb-2 block text-xs text-slate-400">Data i godzina mycia</label><input name="cleaned_at" value="{{ old('cleaned_at',now()->format('Y-m-d\TH:i')) }}" type="datetime-local" required class="w-full rounded-xl bg-[#080b1b] px-4 py-3">@error('cleaned_at')<p class="mt-2 text-sm text-rose-400">{{ $message }}</p>@enderror<button class="mt-3 w-full rounded-xl bg-emerald-500 px-4 py-3 font-semibold text-slate-950">Zapisz mycie</button></form><div class="mt-6 space-y-3"><h3 class="text-sm font-semibold text-slate-300">Historia mycia</h3>@forelse($freezer->cleanings as $cleaning)<article class="rounded-xl bg-white/[0.03] p-4"><div class="flex justify-between gap-3"><div><p class="text-sm text-slate-300">{{ $cleaning->cleaned_at->format('d.m.Y H:i') }}</p><p class="mt-1 text-xs text-slate-600">{{ $cleaning->recorder?->name ?? 'usunięty użytkownik' }}</p></div><div class="text-right"><p class="text-xs text-slate-500">Ważne do</p><b class="text-emerald-300">{{ $cleaning->valid_until->format('d.m.Y') }}</b></div></div></article>@empty<p class="py-8 text-center text-sm text-slate-500">Brak wpisów mycia.</p>@endforelse</div></section>
</div>
</x-warehouse-shell>
