<x-warehouse-shell title="Szczepionki" description="Zarządzanie stanem szczepionek i ich wykorzystaniem w produkcji." root-label="Szczepionki" root-route="vaccines.index">
<x-slot:actions><div class="flex flex-wrap gap-3"><button type="button" onclick="document.querySelector('#new-type').classList.toggle('hidden')" class="rounded-xl border border-indigo-500/40 px-4 py-2.5 text-sm font-semibold text-indigo-300">+ Dodaj nowy typ szczepionki</button><button type="button" onclick="document.querySelector('#new-vaccine').classList.toggle('hidden')" class="rounded-xl bg-indigo-500 px-4 py-2.5 text-sm font-semibold text-white">+ Przyjmij szczepionkę</button></div></x-slot:actions>
<form id="new-type" method="POST" action="{{ route('vaccines.types.store') }}" class="mb-6 {{ $errors->type->any()?'':'hidden' }} rounded-2xl border border-white/[0.06] bg-[#0d1024] p-5">@csrf
    <h2 class="font-semibold text-white">Nowy typ szczepionki</h2><p class="mt-1 text-xs text-slate-500">Typ będzie dostępny podczas przyjmowania kolejnych lotów.</p>
    <div class="mt-4 flex flex-col gap-3 sm:flex-row"><input name="name" value="{{ old('name') }}" required placeholder="Nazwa typu szczepionki" class="min-w-0 flex-1 rounded-xl bg-[#080b1b] px-4 py-3"><button class="rounded-xl bg-emerald-500 px-6 py-3 font-semibold text-slate-950">Dodaj typ</button></div>
    @if($errors->type->any())<p class="mt-3 text-sm text-rose-400">{{ $errors->type->first() }}</p>@endif
</form>
<div class="mb-6 grid gap-4 sm:grid-cols-3">
    <div class="rounded-2xl border border-indigo-500/20 bg-indigo-500/10 p-5"><p class="text-xs font-medium uppercase tracking-wider text-indigo-300">Łączna waga</p><p class="mt-2 text-2xl font-bold text-white">{{ number_format($totalWeight,0,',',' ') }} kg</p></div>
    <div class="rounded-2xl border border-amber-500/10 bg-[#0d1024] p-5"><p class="text-xs font-medium uppercase tracking-wider text-slate-500">Pobrano</p><p class="mt-2 text-2xl font-bold text-amber-300">{{ number_format($totalUsed,0,',',' ') }} kg</p></div>
    <div class="rounded-2xl border border-emerald-500/10 bg-[#0d1024] p-5"><p class="text-xs font-medium uppercase tracking-wider text-slate-500">Pozostało</p><p class="mt-2 text-2xl font-bold text-emerald-300">{{ number_format($remainingWeight,0,',',' ') }} kg</p></div>
</div>
<form id="new-vaccine" method="POST" action="{{ route('vaccines.store') }}" class="mb-6 {{ $errors->any()?'':'hidden' }} rounded-2xl border border-white/[0.06] bg-[#0d1024] p-5">@csrf
    <h2 class="font-semibold text-white">Przyjęcie szczepionki</h2>
    <div class="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-4">
        <div><label class="mb-2 block text-xs text-slate-400">Typ szczepionki</label><select name="type" required class="w-full rounded-xl bg-[#080b1b] px-4 py-3"><option value="">Wybierz typ</option>@foreach($types as $type)<option value="{{ $type->name }}" @selected(old('type')===$type->name)>{{ $type->name }}</option>@endforeach</select>@if($types->isEmpty())<p class="mt-2 text-xs text-amber-300">Najpierw dodaj typ szczepionki.</p>@endif</div>
        <div><label class="mb-2 block text-xs text-slate-400">Numer lotu</label><input name="lot_number" value="{{ old('lot_number') }}" required class="w-full rounded-xl bg-[#080b1b] px-4 py-3"></div>
        <div><label class="mb-2 block text-xs text-slate-400">Data przyjęcia</label><input name="received_at" value="{{ old('received_at',now()->format('Y-m-d')) }}" type="date" required class="w-full rounded-xl bg-[#080b1b] px-4 py-3"></div>
        <div><label class="mb-2 block text-xs text-slate-400">Waga początkowa (kg)</label><input name="weight_kg" value="{{ old('weight_kg') }}" type="number" min="0.001" step="0.001" required class="w-full rounded-xl bg-[#080b1b] px-4 py-3"></div>
    </div>
    @if($errors->any())<p class="mt-3 text-sm text-rose-400">{{ $errors->first() }}</p>@endif
    <div class="mt-5 flex justify-end"><button class="rounded-xl bg-emerald-500 px-6 py-3 font-semibold text-slate-950">Zapisz szczepionkę</button></div>
</form>
<section class="overflow-hidden rounded-2xl border border-white/[0.06] bg-[#0d1024]"><div class="overflow-x-auto"><table class="w-full min-w-[850px] text-left text-sm">
<thead class="border-b border-white/[0.06] text-[10px] uppercase tracking-wider text-slate-600"><tr><th class="px-5 py-4">Typ</th><th class="px-5 py-4">Lot</th><th class="px-5 py-4">Data przyjęcia</th><th class="px-5 py-4 text-right">Waga</th><th class="px-5 py-4 text-right">Pobrano</th><th class="px-5 py-4 text-right">Pozostało</th><th class="px-5 py-4">Status</th><th></th></tr></thead>
<tbody>@forelse($lots as $lot)<tr class="border-b border-white/[0.04] last:border-0 hover:bg-white/[0.02]"><td class="px-5 py-4 font-semibold text-white">{{ $lot->type }}</td><td class="px-5 py-4 text-slate-300">{{ $lot->lot_number }}</td><td class="px-5 py-4 text-slate-400">{{ $lot->received_at->format('d.m.Y') }}</td><td class="px-5 py-4 text-right text-white">{{ number_format((float)$lot->weight_kg,0,',',' ') }} kg</td><td class="px-5 py-4 text-right text-amber-300">{{ number_format((float)$lot->usages_sum_quantity_kg,0,',',' ') }} kg</td><td class="px-5 py-4 text-right font-semibold text-indigo-300">{{ number_format($lot->remaining_weight,0,',',' ') }} kg</td><td class="px-5 py-4"><span class="rounded-full px-2.5 py-1 text-xs {{ $lot->is_active?'bg-emerald-500/10 text-emerald-300':'bg-slate-500/10 text-slate-400' }}">{{ $lot->is_active?'Aktywny':'Nieaktywny' }}</span></td><td class="px-5 py-4 text-right"><a href="{{ route('vaccines.show',$lot) }}" class="rounded-lg border border-white/10 px-3 py-2 text-xs hover:text-indigo-300">Szczegóły</a></td></tr>@empty<tr><td colspan="8" class="px-5 py-20 text-center text-slate-500">Brak przyjętych szczepionek.</td></tr>@endforelse</tbody>
</table></div>@if($lots->hasPages())<div class="border-t border-white/[0.06] p-4">{{ $lots->links() }}</div>@endif</section>
</x-warehouse-shell>
